PACKAGE_NAME="tas58xx"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="tas58xx"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make KERNELRELEASE=${kernelver} KDIR=${kernel_source_dir} clean"

AUTOINSTALL="yes"
